name: CI

on:
  push:
    branches:
      - main
    
permissions: 
  contents: read

jobs:
  code-coverage:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
    - uses: arjundashrath/harden-runner@v0.0.1
